#!/usr/bin/env bash
# Materialize Codex's selected model and visible catalog in agents.conf.

set -euo pipefail

AGENTS_CONFIG_FILE="${AGENTS_CONFIG_FILE:-$HOME/.claude/config/agents.conf}"
CODEX_CONFIG_FILE="${CODEX_CONFIG_FILE:-$HOME/.codex/config.toml}"
CODEX_MODELS_CACHE_FILE="${CODEX_MODELS_CACHE_FILE:-$HOME/.codex/models_cache.json}"
CODEX_CATALOG_SYNC_STATE_FILE="${CODEX_CATALOG_SYNC_STATE_FILE:-$HOME/.local/state/codex-agent-catalog-sync/last_success}"
CHECK_ONLY=false

if [[ "${1:-}" == "--check" ]]; then
    CHECK_ONLY=true
elif [[ $# -ne 0 ]]; then
    echo "usage: $0 [--check]" >&2
    exit 2
fi

fail() {
    echo "ERROR: $*" >&2
    exit 1
}

command -v jq >/dev/null || fail "jq is required"
[[ -f "$AGENTS_CONFIG_FILE" ]] || fail "agent registry not found: $AGENTS_CONFIG_FILE"
[[ -f "$CODEX_CONFIG_FILE" ]] || fail "Codex config not found: $CODEX_CONFIG_FILE"
[[ -f "$CODEX_MODELS_CACHE_FILE" ]] || fail "Codex model cache not found: $CODEX_MODELS_CACHE_FILE"

codex_model="$({
    awk '
        /^[[:space:]]*\[/ { exit }
        /^[[:space:]]*model[[:space:]]*=[[:space:]]*"/ {
            line = $0
            sub(/^[^=]*=[[:space:]]*"/, "", line)
            sub(/".*$/, "", line)
            print line
            exit
        }
    ' "$CODEX_CONFIG_FILE"
})"
[[ -n "$codex_model" ]] || fail "top-level Codex model is missing from $CODEX_CONFIG_FILE"
[[ "$codex_model" =~ ^[[:alnum:]][[:alnum:].:/_-]*$ ]] \
    || fail "Codex model contains unsupported characters: $codex_model"

models_text="$(
    jq -er '
        if (.models | type) != "array" then
            error("models must be an array")
        else
            [
                .models[]
                | select(.visibility == "list")
                | .slug
                | select(type == "string" and length > 0)
            ] as $models
            | if ($models | length) == 0 then
                error("visible model catalog is empty")
            elif ($models | unique | length) != ($models | length) then
                error("visible model catalog contains duplicate slugs")
            else
                $models[]
            end
        end
    ' "$CODEX_MODELS_CACHE_FILE"
)" || fail "invalid Codex model cache: $CODEX_MODELS_CACHE_FILE"

models=()
selected_is_visible=false
while IFS= read -r model; do
    [[ "$model" =~ ^[[:alnum:]][[:alnum:].:/_-]*$ ]] \
        || fail "model slug contains unsupported characters: $model"
    models+=("$model")
    [[ "$model" == "$codex_model" ]] && selected_is_visible=true
done <<< "$models_text"

if [[ "$selected_is_visible" == false ]]; then
    models=("$codex_model" "${models[@]}")
fi

tmp_file="$(mktemp "${AGENTS_CONFIG_FILE}.XXXXXX")"
cleanup() {
    rm -f "$tmp_file"
}
trap cleanup EXIT

in_codex=false
in_codex_models=false
saw_codex_model=false
saw_codex_models=false

while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^\[([^]]+)\]$ ]]; then
        if [[ "$in_codex_models" == true ]]; then
            printf '\n' >> "$tmp_file"
        fi

        section="${BASH_REMATCH[1]}"
        in_codex=false
        in_codex_models=false
        case "$section" in
            codex)
                in_codex=true
                ;;
            codex.models)
                in_codex_models=true
                saw_codex_models=true
                printf '%s\n' "$line" >> "$tmp_file"
                printf '# Generated by scripts/agents/sync_codex_catalog.sh.\n' >> "$tmp_file"
                printf '%s\n' "${models[@]}" >> "$tmp_file"
                continue
                ;;
        esac
    fi

    if [[ "$in_codex_models" == true ]]; then
        continue
    fi
    if [[ "$in_codex" == true && "$line" =~ ^model= ]]; then
        printf 'model=%s\n' "$codex_model" >> "$tmp_file"
        saw_codex_model=true
        continue
    fi
    printf '%s\n' "$line" >> "$tmp_file"
done < "$AGENTS_CONFIG_FILE"

[[ "$saw_codex_model" == true ]] || fail "[codex] model entry not found in $AGENTS_CONFIG_FILE"
[[ "$saw_codex_models" == true ]] || fail "[codex.models] section not found in $AGENTS_CONFIG_FILE"

if cmp -s "$tmp_file" "$AGENTS_CONFIG_FILE"; then
    if [[ "$CHECK_ONLY" == false ]]; then
        mkdir -p "$(dirname "$CODEX_CATALOG_SYNC_STATE_FILE")"
        touch "$CODEX_CATALOG_SYNC_STATE_FILE"
    fi
    echo "Codex agent catalog is current."
    exit 0
fi

if [[ "$CHECK_ONLY" == true ]]; then
    echo "Codex agent catalog is stale: $AGENTS_CONFIG_FILE" >&2
    exit 1
fi

chmod "$(stat -f '%Lp' "$AGENTS_CONFIG_FILE")" "$tmp_file"
mv "$tmp_file" "$AGENTS_CONFIG_FILE"
trap - EXIT
mkdir -p "$(dirname "$CODEX_CATALOG_SYNC_STATE_FILE")"
touch "$CODEX_CATALOG_SYNC_STATE_FILE"
echo "Updated Codex agent catalog: $AGENTS_CONFIG_FILE"
