#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SYNC_SCRIPT="$SCRIPT_DIR/sync_codex_catalog.sh"
TEST_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sync-codex-catalog.XXXXXX")"
trap 'rm -rf "$TEST_DIR"' EXIT

AGENTS="$TEST_DIR/agents.conf"
CODEX_CONFIG="$TEST_DIR/config.toml"
MODELS_CACHE="$TEST_DIR/models_cache.json"
SYNC_STATE="$TEST_DIR/state/last_success"

write_agents_fixture() {
    printf '%s\n' \
        '[codex]' \
        'model=gpt-old' \
        'effort=' \
        '' \
        '[codex.models]' \
        'gpt-old' \
        '' \
        '[codex.efforts]' \
        'high' \
        '' \
        '[claude]' \
        'model=sonnet' > "$AGENTS"
}

write_agents_fixture
printf '%s\n' 'model = "gpt-new"' 'model_reasoning_effort = "high"' > "$CODEX_CONFIG"
printf '%s\n' \
    '{"models":[' \
    '{"slug":"gpt-new","visibility":"list"},' \
    '{"slug":"gpt-other","visibility":"list"},' \
    '{"slug":"internal","visibility":"hide"}' \
    ']}' > "$MODELS_CACHE"

AGENTS_CONFIG_FILE="$AGENTS" \
CODEX_CONFIG_FILE="$CODEX_CONFIG" \
CODEX_MODELS_CACHE_FILE="$MODELS_CACHE" \
CODEX_CATALOG_SYNC_STATE_FILE="$SYNC_STATE" \
    "$SYNC_SCRIPT" >/dev/null

expected="$TEST_DIR/expected.conf"
printf '%s\n' \
    '[codex]' \
    'model=gpt-new' \
    'effort=' \
    '' \
    '[codex.models]' \
    '# Generated by scripts/agents/sync_codex_catalog.sh.' \
    'gpt-new' \
    'gpt-other' \
    '' \
    '[codex.efforts]' \
    'high' \
    '' \
    '[claude]' \
    'model=sonnet' > "$expected"
cmp "$expected" "$AGENTS"

AGENTS_CONFIG_FILE="$AGENTS" \
CODEX_CONFIG_FILE="$CODEX_CONFIG" \
CODEX_MODELS_CACHE_FILE="$MODELS_CACHE" \
CODEX_CATALOG_SYNC_STATE_FILE="$SYNC_STATE" \
    "$SYNC_SCRIPT" --check >/dev/null

before="$TEST_DIR/before-invalid.conf"
cp "$AGENTS" "$before"
printf '%s\n' '{invalid' > "$MODELS_CACHE"
if AGENTS_CONFIG_FILE="$AGENTS" \
    CODEX_CONFIG_FILE="$CODEX_CONFIG" \
    CODEX_MODELS_CACHE_FILE="$MODELS_CACHE" \
    CODEX_CATALOG_SYNC_STATE_FILE="$SYNC_STATE" \
    "$SYNC_SCRIPT" >/dev/null 2>&1; then
    echo "invalid cache unexpectedly succeeded" >&2
    exit 1
fi
cmp "$before" "$AGENTS"

echo "sync_codex_catalog tests passed"
