#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SYNC_SCRIPT="$SCRIPT_DIR/sync_codex_catalog.sh"
TEST_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sync-codex-catalog.XXXXXX")"
trap 'rm -rf "$TEST_DIR"' EXIT

AGENTS="$TEST_DIR/agents.conf"
CODEX_CONFIG="$TEST_DIR/config.toml"
MODELS_CACHE="$TEST_DIR/models_cache.json"
SYNC_STATE="$TEST_DIR/state/last_success"
STDERR_FILE="$TEST_DIR/stderr"
FAKE_BIN="$TEST_DIR/bin"

mkdir -p "$FAKE_BIN"
cat > "$FAKE_BIN/claude" <<'EOF'
#!/usr/bin/env bash
if [[ "${CLAUDE_HELP_MODE:-aliases}" == "aliases" ]]; then
    cat <<'HELP'
Usage: claude [options]
  --model <model>  Model for the session. Use an alias (e.g.
                   'fable', 'opus', or 'sonnet') or a full name.
  --print          Print response and exit.
HELP
else
    echo 'Usage: claude [options]'
    echo '  --print  Print response and exit.'
fi
EOF
chmod +x "$FAKE_BIN/claude"

fail() {
    echo "$1" >&2
    exit 1
}

run_sync() {
    PATH="$FAKE_BIN:$PATH" \
    AGENTS_CONFIG_FILE="$AGENTS" \
    CODEX_CONFIG_FILE="$CODEX_CONFIG" \
    CODEX_MODELS_CACHE_FILE="$MODELS_CACHE" \
    CODEX_CATALOG_SYNC_STATE_FILE="$SYNC_STATE" \
        "$SYNC_SCRIPT" "$@"
}

assert_contains() {
    local text="$1" expected="$2" description="$3"
    [[ "$text" == *"$expected"* ]] || fail "$description"
}

cat > "$AGENTS" <<'EOF'
[codex]
model=gpt-legacy
effort=medium

[codex.models]
# Legacy catalog must remain unchanged.
gpt-legacy

[codex.efforts]
medium
high

[assignments]
cleanfix=codex

[cleanfix.codex]
style_eval=gpt-new:high

[codex.agents]
# Old generated body.
gpt-legacy=medium
gpt-new=low,medium,high

[claude.agents]
fable=low,medium,high,max
sonnet=low,medium,high,max
EOF
cp "$AGENTS" "$TEST_DIR/legacy-before.conf"

printf '%s\n' 'model = "gpt-selected"' 'model_reasoning_effort = "high"' > "$CODEX_CONFIG"
cat > "$MODELS_CACHE" <<'EOF'
{"models":[
  {"slug":"gpt-new","visibility":"list","supported_reasoning_levels":[{"effort":"medium"},{"effort":"high"},{"effort":"xhigh"}]},
  {"slug":"gpt-empty","visibility":"list"},
  {"slug":"bad:slug","visibility":"list","supported_reasoning_levels":[{"effort":"high"}]},
  {"slug":"gpt-selected","visibility":"hide","supported_reasoning_levels":[{"effort":"low"},{"effort":"high"}]},
  {"slug":"internal","visibility":"hide"}
]}
EOF

before_check="$TEST_DIR/before-stale-check.conf"
cp "$AGENTS" "$before_check"
if run_sync --check >/dev/null 2>"$STDERR_FILE"; then
    fail "--check accepted a stale catalog"
fi
cmp "$before_check" "$AGENTS" || fail "--check changed a stale catalog"

if ! run_sync >/dev/null 2>"$STDERR_FILE"; then
    sed -n '1,120p' "$STDERR_FILE" >&2
    fail "initial catalog sync failed"
fi
stderr_text="$(<"$STDERR_FILE")"
assert_contains "$stderr_text" "skipping Codex model 'bad:slug'" \
    "colon-bearing slug did not produce a warning"
assert_contains "$stderr_text" "Claude model alias 'opus' is missing from [claude.agents]" \
    "missing Claude alias did not produce a warning"

expected="$TEST_DIR/expected.conf"
cat > "$expected" <<'EOF'
[codex]
model=gpt-legacy
effort=medium

[codex.models]
# Legacy catalog must remain unchanged.
gpt-legacy

[codex.efforts]
medium
high

[assignments]
cleanfix=codex

[cleanfix.codex]
style_eval=gpt-new:high

[codex.agents]
# Generated by scripts/agents/sync_codex_catalog.sh — do not hand-edit.
gpt-selected=low,high
gpt-new=medium,high,xhigh
gpt-empty=

[claude.agents]
fable=low,medium,high,max
sonnet=low,medium,high,max
EOF
cmp "$expected" "$AGENTS" || fail "sync wrote the wrong [codex.agents] output"

before_legacy="$TEST_DIR/legacy-prefix-before"
after_legacy="$TEST_DIR/legacy-prefix-after"
sed -n '1,/^\[codex.agents\]$/p' "$TEST_DIR/legacy-before.conf" | sed '$d' > "$before_legacy"
sed -n '1,/^\[codex.agents\]$/p' "$AGENTS" | sed '$d' > "$after_legacy"
cmp "$before_legacy" "$after_legacy" || fail "sync changed a legacy registry section"

run_sync --check >/dev/null 2>"$STDERR_FILE" \
    || fail "--check rejected a current catalog"

CLAUDE_HELP_MODE=unparseable run_sync --check >/dev/null 2>"$STDERR_FILE" \
    || fail "unparseable Claude help changed --check behavior"
stderr_text="$(<"$STDERR_FILE")"
[[ "$stderr_text" != *"Claude model alias"* ]] \
    || fail "unparseable Claude help produced an alias warning"

cat > "$AGENTS" <<'EOF'
[assignments]
cleanfix=codex

[cleanfix.codex]
style_eval=gpt-new:high

[codex.agents]
gpt-new=high

[claude.agents]
fable=low,medium,high,max
opus=low,medium,high,max
sonnet=low,medium,high,max
EOF
printf '%s\n' 'model = "gpt-uncached"' > "$CODEX_CONFIG"
run_sync >/dev/null 2>"$STDERR_FILE" \
    || fail "sync required a legacy section"
stderr_text="$(<"$STDERR_FILE")"
[[ "$stderr_text" != *"Claude model alias"* && "$stderr_text" != *"is assigned to"* ]] \
    || fail "new-sections-only sync produced an unexpected registry warning"
grep -q '^gpt-empty=$' "$AGENTS" || fail "model without reasoning levels did not get an empty effort list"
grep -q '^gpt-uncached=$' "$AGENTS" || fail "uncached selected model did not get an empty effort list"
if grep -q '^bad:slug=' "$AGENTS"; then
    fail "colon-bearing slug was written to [codex.agents]"
fi

cat > "$AGENTS" <<'EOF'
[assignments]
cleanfix=codex

[cleanfix.codex]
style_eval=gpt-retired:high
report=gpt-retired:medium

[codex.agents]
gpt-retired=low,medium,high,xhigh
gpt-current=medium,high

[claude.agents]
fable=low,medium,high,max
opus=low,medium,high,max
sonnet=low,medium,high,max
EOF
printf '%s\n' 'model = "gpt-retired"' > "$CODEX_CONFIG"
cat > "$MODELS_CACHE" <<'EOF'
{"models":[
  {"slug":"gpt-current","visibility":"list","supported_reasoning_levels":[{"effort":"medium"},{"effort":"high"}]}
]}
EOF
run_sync >/dev/null 2>"$STDERR_FILE"
stderr_text="$(<"$STDERR_FILE")"
assert_contains "$stderr_text" "cleanfix.style_eval is assigned to 'gpt-retired'" \
    "stale style_eval row warning did not name the row"
assert_contains "$stderr_text" "/agent cleanfix.style_eval <agent>[:<effort>]" \
    "stale row warning did not name the task reconfiguration command"
assert_contains "$stderr_text" "/agent cleanfix <family>" \
    "stale row warning did not name the family reconfiguration command"
assert_contains "$stderr_text" "cleanfix.report is assigned to 'gpt-retired'" \
    "sync did not warn once for each stale assigned row"
[[ "$(grep -c "is assigned to 'gpt-retired'" "$STDERR_FILE")" -eq 2 ]] \
    || fail "sync emitted the wrong number of stale-row warnings"
[[ "$(grep -c '^gpt-retired=low,medium,high,xhigh$' "$AGENTS")" -eq 1 ]] \
    || fail "retired assigned agent's previous catalog row was not preserved exactly once"

before="$TEST_DIR/before-invalid.conf"
cp "$AGENTS" "$before"
printf '%s\n' '{invalid' > "$MODELS_CACHE"
if run_sync >/dev/null 2>&1; then
    fail "invalid cache unexpectedly succeeded"
fi
cmp "$before" "$AGENTS" || fail "invalid cache changed the registry"

echo "sync_codex_catalog tests passed"
